DROP DATABASE IF EXISTS Assignment2;
CREATE DATABASE Assignment2;

USE Assignment2;

CREATE TABLE user (
	user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Firstname VARCHAR(32) NOT NULL,
	Lastname VARCHAR(32) NOT NULL,
	Password VARCHAR(32) NOT NULL,
	Email VARCHAR(32) NOT NULL
);